source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'
gem 'rails', '~> 6.1.4'
gem 'pg', '~> 0.18.4'
gem 'puma', '~> 5.4.0'
gem 'jbuilder', '~> 2.11.2'
gem 'bootsnap', '~> 1.7.7', require: false

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.6.0'
  gem 'spring'
end